#!/bin/bash
set -e

main() {
  # https://stackoverflow.com/a/246128/3837223
  SCRIPT_PATH="$(
    cd -- "$(dirname "$0")" >/dev/null 2>&1
    pwd -P
  )"

  echo "current dir: $(pwd)"
  echo "script path: $SCRIPT_PATH"
  echo

  # get the latest package lists
  sudo apt update

  (
    cd "$SCRIPT_PATH"
    ./debian/install_xubuntu_desktop
    ./debian/install_firefox
    ./debian/install_vs_code_aarch64
    ./install_asdf_bash
    ./install_elixir
    ./install_nerves_systems
  )

  echo "Done"
}

main "$@"
