#!/bin/bash
set -e

echo '===> Fetch the latest package info and upgrade all the packages'

sudo pacman -Syu --noconfirm

echo '===> Install microcode updates tools'

# https://wiki.archlinux.org/title/microcode
sudo pacman -S --needed --noconfirm intel-ucode

echo '===> Install additional package managers'

# https://docs.flatpak.org
sudo pacman -S --needed --noconfirm flatpak

# https://asdf-vm.com
./shared/install_asdf.sh

# https://github.com/Jguer/yay#installation
YAY_SRC_DIR="$HOME/Downloads/yay"

if [[ -d "$YAY_SRC_DIR" ]]; then
  echo "warning: yay is already installed -- skipping"
else
  sudo pacman -S --needed --noconfirm base-devel git

  git clone https://aur.archlinux.org/yay-bin.git "$YAY_SRC_DIR" &&
    cd "$YAY_SRC_DIR" && makepkg -si
fi

echo '===> Install basic tools'

# other tools I want to install
sudo pacman -S --needed --noconfirm \
  code \
  diff-so-fancy \
  direnv \
  fzf \
  git \
  git-delta \
  github-cli \
  htop \
  lazygit \
  man-db \
  ncdu \
  neofetch \
  neovim \
  net-tools \
  ranger \
  ripgrep \
  rofi \
  rsync \
  shfmt \
  speech-dispatcher \
  tmux \
  trash-cli \
  xclip \
  xdotool \
  xsel

yay -S --needed --noconfirm \
  git-open

echo '===> Install basic GUI apps'

flathub_packages=(
  com.brave.Browser
  com.discordapp.Discord
  com.slack.Slack
  com.transmissionbt.Transmission
  com.uploadedlobster.peek
  org.flameshot.Flameshot
  org.gimp.GIMP
  org.gnome.Calculator
  org.gnome.Evince
  org.gnome.Loupe
  org.kde.arianna
  org.libreoffice.LibreOffice
  org.videolan.VLC
)

for pkg in "${flathub_packages[@]}"; do
  flatpak install -y --noninteractive flathub "$pkg"
done

sudo pacman -S --needed --noconfirm \
  gnome-screenshot \
  virt-manager

yay -S --needed --noconfirm \
  1password \
  freetube-bin \
  webapp-manager \
  ytmdesktop-git

echo '===> Install backup tools'

sudo pacman -S --needed --noconfirm \
  grsync \
  rsync \
  timeshift

echo '===> Install firewall'

sudo pacman -S --needed --noconfirm ufw

echo '===> Install docker'

# https://wiki.archlinux.org/title/docker
sudo pacman -S --needed --noconfirm \
  docker \
  docker-compose

echo '===> Install virtualbox'

# virtualbox for kernels other than the "linux" kernel
# https://wiki.archlinux.org/title/VirtualBox
sudo pacman -S --needed --noconfirm \
  virtualbox \
  virtualbox-host-dkms

echo '===> Install ohmyzsh'

sudo pacman -S --needed --noconfirm zsh

./shared/install_ohmyzsh.sh

echo '===> Install Japanese input method'

sudo pacman -S --needed --noconfirm \
  fcitx5-im \
  fcitx5-mozc

echo '===> Install fonts'

# https://wiki.archlinux.org/title/Localization/Japanese
sudo pacman -S --needed --noconfirm \
  noto-fonts \
  noto-fonts-cjk \
  noto-fonts-emoji \
  noto-fonts-extra \
  otf-ipaexfont \
  otf-ipafont \
  ttf-firacode-nerd

echo '===> Install greenclip'

./shared/install_greenclip.sh

echo '===> Install jetpack'

./shared/install_jetpack.sh

echo '===> Install asdf plugins'

# https://github.com/asdf-vm/asdf-erlang
sudo pacman -S --needed --noconfirm \
  base-devel \
  ncurses \
  glu mesa wxwidgets-gtk3 libpng \
  libssh \
  unixodbc \
  libxslt fop

# https://github.com/asdf-vm/asdf-elixir
sudo pacman -S --needed --noconfirm unzip

asdf_plugins=(
  erlang
  elixir
  nodejs
)

for plugin in "${asdf_plugins[@]}"; do
  asdf plugin add "$plugin"
  asdf install "$plugin" latest
  asdf global "$plugin" latest
done

asdf list
