#!/bin/bash
set -e

#
# This is a post-install script for setting up the Nerves firmware development
# environment on Ubuntu ARM 64-bit machines.
#

main() {
  # https://stackoverflow.com/a/246128/3837223
  SCRIPT_PATH="$(
    cd -- "$(dirname "$0")" >/dev/null 2>&1
    pwd -P
  )"

  echo "current dir: $(pwd)"
  echo "script path: $SCRIPT_PATH"
  echo

  # get the latest package lists
  sudo apt update

  (
    cd "$SCRIPT_PATH"
    ./ubuntu/install_xubuntu_desktop
    ./ubuntu/install_firefox
    ./ubuntu_arm64/install_vs_code
    ./ubuntu/install_zsh
    ./ubuntu/chsh_zsh
    ./ubuntu/install_ohmyzsh
    ./install_asdf_zsh
    ./install_erlang_and_elixir
    ./install_nerves_systems
  )

  echo "Done"
}

main "$@"
