#!/bin/bash

echo '===> Install packages with apt'
sudo apt update && sudo apt upgrade

sudo apt install -y \
  curl \
  direnv \
  flameshot \
  git \
  neofetch \
  ranger \
  rofi \
  stacer \
  tmux \
  wget \
  xclip \
  xsel \
  virt-manager \
  zsh

echo '===> Set up zsh'
# https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH#install-and-set-up-zsh-as-default
chsh -s "$(which zsh)"

# https://ohmyz.sh/#install
# https://github.com/ohmyzsh/ohmyzsh/tree/master#unattended-install
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

echo '===> Set up asdf'

git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.12.0
asdf update

plugins=(
  erlang
  elixir
  neovim
  delta
  fzf
  lua
  nodejs
  ripgrep
  shfmt
  zig
)

for plugin in "${plugins[@]}"; do
  asdf plugin add "$plugin"
  asdf install "$plugin" latest
  asdf global "$plugin" latest
done

asdf list

echo '===> Install FiraCodeNerdFont'
if fc-list | grep -q FiraCodeNerdFont; then
  echo "already installed"
else
  PATCHED_FONTS_BASE_URL="https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts"
  FONT_URL="$PATCHED_FONTS_BASE_URL/FiraCode/Regular/FiraCodeNerdFont-Regular.ttf"
  FONT_DIR="$HOME/.local/share/fonts"
  mkdir -p "$FONT_DIR"
  cd "$FONT_DIR" && curl -fLO "$FONT_URL"
  fc-list | grep Nerd
fi

echo '===> Install greenclip'
if command -v greenclip &>/dev/null; then
  echo "already installed"
else
  LOCAL_BIN_DIR="$HOME/.local/bin"
  mkdir -p "$LOCAL_BIN_DIR"
  wget https://github.com/erebe/greenclip/releases/download/v4.2/greenclip -P "$LOCAL_BIN_DIR"
  chmod +x "$LOCAL_BIN_DIR/greenclip"
fi

echo '===> Install Docker Engine'
if command -v docker &>/dev/null; then
  echo "already installed"
else
  sudo apt install uidmap -y

  # Install Docker Engine
  # https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script
  curl -fsSL https://get.docker.com -o get-docker.sh
  sudo sh ./get-docker.sh

  # Run the Docker daemon as a non-root user (Rootless mode)
  # https://docs.docker.com/engine/security/rootless
  /usr/bin/dockerd-rootless-setuptool.sh install
fi

