#!/bin/bash
set -e

echo "==> Installing VS Code"

if command -v code &>/dev/null; then
  echo "vs code is already installed"
else
  sudo apt install wget -y
  wget -O code.deb "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-arm64"
  sudo dpkg -i code.deb
  rm code.deb
fi
