#!/bin/bash
set -e

echo "==> Installing VS Code"

if command -v code &>/dev/null; then
  echo "vs code is already installed"
else
  flatpak install flathub com.visualstudio.code
  flatpak run com.visualstudio.code
fi
